# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='images')),
                ('image_second', django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='images')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], default='Unresolved', max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('user_id', models.CharField(db_column='User_id', max_length=11, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('user_password', models.CharField(db_column='User_password', max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
